// examples/react/src/pages/CalendarPage.tsx
import { useState } from 'react';
import { usePlugin, useBridge } from '../bridge';
import { calendar } from '@example/plugins';

function CalendarPage() {
  const { connectionMode } = useBridge();
  const { addEvent, getEvents } = usePlugin(calendar);
  const [title, setTitle] = useState('');
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [notes, setNotes] = useState('');

  const handleAdd = async () => {
    const res = await addEvent.execute({
      title,
      startDate: new Date(startDate).toISOString(),
      endDate: new Date(endDate).toISOString(),
      notes: notes || undefined,
    });
    if (res) {
      setTitle('');
      setNotes('');
    }
  };

  const handleGetEvents = () => {
    const now = new Date();
    const start = new Date(now.getFullYear(), now.getMonth(), 1).toISOString();
    const end = new Date(now.getFullYear(), now.getMonth() + 1, 0).toISOString();
    getEvents.execute({ startDate: start, endDate: end });
  };

  const events = getEvents.data?.events ?? [];
  const error = addEvent.error ?? getEvents.error;

  return (
    <div>
      <h1>Calendar</h1>
      <p className="mode-badge">
        {connectionMode === 'native'
          ? 'Native Bridge'
          : connectionMode === 'fallback'
            ? 'Fallback (In-Memory)'
            : 'Disconnected'}
      </p>

      <div className="card">
        <h2>Add Event</h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="Event title"
            style={{ padding: '8px', borderRadius: '6px', border: '1px solid #ddd' }}
          />
          <input
            type="datetime-local"
            value={startDate}
            onChange={(e) => setStartDate(e.target.value)}
            style={{ padding: '8px', borderRadius: '6px', border: '1px solid #ddd' }}
          />
          <input
            type="datetime-local"
            value={endDate}
            onChange={(e) => setEndDate(e.target.value)}
            style={{ padding: '8px', borderRadius: '6px', border: '1px solid #ddd' }}
          />
          <input
            type="text"
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            placeholder="Notes (optional)"
            style={{ padding: '8px', borderRadius: '6px', border: '1px solid #ddd' }}
          />
          <button
            className="button"
            onClick={handleAdd}
            disabled={!title || !startDate || !endDate}
          >
            Add to Calendar
          </button>
        </div>
        {addEvent.data && (
          <div className="result success">Event created (id: {addEvent.data.id})</div>
        )}
      </div>

      <div className="card">
        <h2>This Month</h2>
        <button className="button button-secondary" onClick={handleGetEvents}>
          Load Events
        </button>
        {events.length > 0 && (
          <div style={{ marginTop: '8px' }}>
            {events.map((evt) => (
              <div key={evt.id} className="result" style={{ marginBottom: '4px' }}>
                <strong>{evt.title}</strong>
                <br />
                <span style={{ fontSize: '11px', color: '#666' }}>
                  {new Date(evt.startDate).toLocaleString()}
                </span>
              </div>
            ))}
          </div>
        )}
      </div>

      {error && <div className="result error">{error.message}</div>}
    </div>
  );
}

export default CalendarPage;

// examples/vue/src/pages/CalendarPage.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { usePlugin, useBridge } from '../bridge';
import { calendar } from '@example/plugins';

const { connectionMode } = useBridge();
const { addEvent, getEvents } = usePlugin(calendar);

const title = ref('');
const startDate = ref('');
const endDate = ref('');
const notes = ref('');

const handleAdd = async () => {
  const res = await addEvent.execute({
    title: title.value,
    startDate: new Date(startDate.value).toISOString(),
    endDate: new Date(endDate.value).toISOString(),
    notes: notes.value || undefined,
  });
  if (res) {
    title.value = '';
    notes.value = '';
  }
};

const handleGetEvents = () => {
  const now = new Date();
  const start = new Date(now.getFullYear(), now.getMonth(), 1).toISOString();
  const end = new Date(now.getFullYear(), now.getMonth() + 1, 0).toISOString();
  getEvents.execute({ startDate: start, endDate: end });
};

const events = computed(() => (getEvents.data.value as any)?.events ?? []);
const error = computed(() => addEvent.error.value ?? getEvents.error.value);
</script>

<template>
  <div>
    <h1>Calendar</h1>
    <p class="mode-badge">
      {{ connectionMode === 'native' ? 'Native Bridge'
        : connectionMode === 'fallback' ? 'Fallback (In-Memory)'
        : 'Disconnected' }}
    </p>
    <div class="card">
      <h2>Add Event</h2>
      <div style="display: flex; flex-direction: column; gap: 8px">
        <input v-model="title" type="text" placeholder="Event title" style="padding: 8px; border-radius: 6px; border: 1px solid #ddd" />
        <input v-model="startDate" type="datetime-local" style="padding: 8px; border-radius: 6px; border: 1px solid #ddd" />
        <input v-model="endDate" type="datetime-local" style="padding: 8px; border-radius: 6px; border: 1px solid #ddd" />
        <input v-model="notes" type="text" placeholder="Notes (optional)" style="padding: 8px; border-radius: 6px; border: 1px solid #ddd" />
        <button class="button" @click="handleAdd" :disabled="!title || !startDate || !endDate">
          Add to Calendar
        </button>
      </div>
      <div v-if="addEvent.data.value" class="result success">Event created (id: {{ addEvent.data.value.id }})</div>
    </div>
    <div class="card">
      <h2>This Month</h2>
      <button class="button button-secondary" @click="handleGetEvents">Load Events</button>
      <div v-if="events.length > 0" style="margin-top: 8px">
        <div v-for="evt in events" :key="evt.id" class="result" style="margin-bottom: 4px">
          <strong>{{ evt.title }}</strong><br />
          <span style="font-size: 11px; color: #666">{{ new Date(evt.startDate).toLocaleString() }}</span>
        </div>
      </div>
    </div>
    <div v-if="error" class="result error">{{ error.message }}</div>
  </div>
</template>
