// apps/example-web/src/App.tsx
import { Routes, Route, Link, useLocation } from 'react-router-dom';
import HomePage from './pages/HomePage';
import CameraPage from './pages/CameraPage';
import LocationPage from './pages/LocationPage';
import StoragePage from './pages/StoragePage';
import BiometricPage from './pages/BiometricPage';
import DevToolsPage from './pages/DevToolsPage';

function App() {
  const location = useLocation();

  const isActive = (path: string) => {
    return location.pathname === path ? 'active' : '';
  };

  return (
    <>
      <nav className="nav">
        <ul>
          <li>
            <Link to="/" className={isActive('/')}>
              Home
            </Link>
          </li>
          <li>
            <Link to="/camera" className={isActive('/camera')}>
              Camera
            </Link>
          </li>
          <li>
            <Link to="/location" className={isActive('/location')}>
              Location
            </Link>
          </li>
          <li>
            <Link to="/storage" className={isActive('/storage')}>
              Storage
            </Link>
          </li>
          <li>
            <Link to="/biometric" className={isActive('/biometric')}>
              Biometric
            </Link>
          </li>
          <li>
            <Link to="/devtools" className={isActive('/devtools')}>
              DevTools
            </Link>
          </li>
        </ul>
      </nav>

      <div className="container">
        <Routes>
          <Route path="/" element={<HomePage />} />
          <Route path="/camera" element={<CameraPage />} />
          <Route path="/location" element={<LocationPage />} />
          <Route path="/storage" element={<StoragePage />} />
          <Route path="/biometric" element={<BiometricPage />} />
          <Route path="/devtools" element={<DevToolsPage />} />
        </Routes>
      </div>
    </>
  );
}

export default App;

// examples/vue/src/App.vue
<script setup lang="ts">
import { useRoute } from 'vue-router';

const route = useRoute();
const isActive = (path: string) => route.path === path ? 'active' : '';
</script>

<template>
  <div class="container page-content">
    <RouterView />
  </div>

  <nav class="nav">
    <ul>
      <li><RouterLink to="/" :class="isActive('/')">Home</RouterLink></li>
      <li><RouterLink to="/camera" :class="isActive('/camera')">Camera</RouterLink></li>
      <li><RouterLink to="/location" :class="isActive('/location')">Location</RouterLink></li>
      <li><RouterLink to="/biometric" :class="isActive('/biometric')">Biometric</RouterLink></li>
      <li><RouterLink to="/phone" :class="isActive('/phone')">Phone</RouterLink></li>
      <li><RouterLink to="/calendar" :class="isActive('/calendar')">Calendar</RouterLink></li>
      <li><RouterLink to="/device" :class="isActive('/device')">Device</RouterLink></li>
      <li><RouterLink to="/share" :class="isActive('/share')">Share</RouterLink></li>
      <li><RouterLink to="/actions" :class="isActive('/actions')">useAction</RouterLink></li>
    </ul>
  </nav>
</template>
