// examples/vue/src/App.vue
<script setup lang="ts">
import { useRoute } from 'vue-router';

const route = useRoute();
const isActive = (path: string) => route.path === path ? 'active' : '';
</script>

<template>
  <div class="container page-content">
    <RouterView />
  </div>

  <nav class="nav">
    <ul>
      <li><RouterLink to="/" :class="isActive('/')">Home</RouterLink></li>
      <li><RouterLink to="/camera" :class="isActive('/camera')">Camera</RouterLink></li>
      <li><RouterLink to="/location" :class="isActive('/location')">Location</RouterLink></li>
      <li><RouterLink to="/biometric" :class="isActive('/biometric')">Biometric</RouterLink></li>
      <li><RouterLink to="/phone" :class="isActive('/phone')">Phone</RouterLink></li>
      <li><RouterLink to="/calendar" :class="isActive('/calendar')">Calendar</RouterLink></li>
      <li><RouterLink to="/device" :class="isActive('/device')">Device</RouterLink></li>
      <li><RouterLink to="/share" :class="isActive('/share')">Share</RouterLink></li>
      <li><RouterLink to="/actions" :class="isActive('/actions')">useAction</RouterLink></li>
    </ul>
  </nav>
</template>

// examples/react/src/App.tsx
import type { ComponentType } from 'react';
import { Link, Route, Routes, useLocation } from 'react-router-dom';

import ActionsPage from './pages/ActionsPage';
import BiometricPage from './pages/BiometricPage';
import CalendarPage from './pages/CalendarPage';
import CameraPage from './pages/CameraPage';
import DevicePage from './pages/DevicePage';
import HomePage from './pages/HomePage';
import LocationPage from './pages/LocationPage';
import MiddlewarePage from './pages/MiddlewarePage';
import PhonePage from './pages/PhonePage';
import SharePage from './pages/SharePage';

const routes: { path: string; label: string; component: ComponentType }[] = [
  { path: '/', label: 'Home', component: HomePage },
  { path: '/camera', label: 'Camera', component: CameraPage },
  { path: '/location', label: 'Location', component: LocationPage },
  { path: '/biometric', label: 'Biometric', component: BiometricPage },
  { path: '/phone', label: 'Phone', component: PhonePage },
  { path: '/calendar', label: 'Calendar', component: CalendarPage },
  { path: '/device', label: 'Device', component: DevicePage },
  { path: '/share', label: 'Share', component: SharePage },
  { path: '/actions', label: 'useAction', component: ActionsPage },
  { path: '/middleware', label: 'Middleware', component: MiddlewarePage },
];

function App() {
  const location = useLocation();

  const isActive = (path: string) => (location.pathname === path ? 'active' : '');

  return (
    <>
      <div className="container page-content">
        <Routes>
          {routes.map(({ path, component: Component }) => (
            <Route key={path} path={path} element={<Component />} />
          ))}
        </Routes>
      </div>

      <nav className="nav">
        <ul>
          {routes.map(({ path, label }) => (
            <li key={path}>
              <Link to={path} className={isActive(path)}>
                {label}
              </Link>
            </li>
          ))}
        </ul>
      </nav>
    </>
  );
}

export default App;
