// examples/vue/src/components/ModeBadge.vue
<script setup lang="ts">
defineProps<{
  connectionMode: string;
  fallbackLabel?: string;
}>();

const MODE_CONFIG: Record<string, string> = {
  native: 'Native Bridge',
  fallback: 'Fallback',
  disconnected: 'Disconnected',
};
</script>

<template>
  <p class="mode-badge">
    {{
      connectionMode === 'fallback' && fallbackLabel
        ? fallbackLabel
        : (MODE_CONFIG[connectionMode] ?? connectionMode)
    }}
  </p>
</template>

// examples/react/src/components/ModeBadge.tsx
type ConnectionMode = 'native' | 'fallback' | 'disconnected';

const MODE_CONFIG: Record<ConnectionMode, { className: string; label: string }> = {
  native: { className: 'status-connected', label: 'Native Bridge' },
  fallback: { className: 'status-fallback', label: 'Fallback' },
  disconnected: { className: 'status-disconnected', label: 'Disconnected' },
};

export function getModeLabel(connectionMode: ConnectionMode, fallbackLabel?: string): string {
  const config = MODE_CONFIG[connectionMode];
  if (fallbackLabel && connectionMode === 'fallback') {
    return `Fallback (${fallbackLabel})`;
  }
  return config.label;
}

export function getModeClassName(connectionMode: ConnectionMode): string {
  return MODE_CONFIG[connectionMode].className;
}

interface ModeBadgeProps {
  connectionMode: ConnectionMode;
  fallbackLabel?: string;
}

function ModeBadge({ connectionMode, fallbackLabel }: ModeBadgeProps) {
  return <p className="mode-badge">{getModeLabel(connectionMode, fallbackLabel)}</p>;
}

export default ModeBadge;
