// examples/vue/src/pages/DevicePage.vue
<script setup lang="ts">
import { usePlugin, useBridge } from '../bridge';
import { device } from '@example/plugins';
import type { DeviceInfoResponse } from '@example/plugins';
import { computed } from 'vue';
import ModeBadge from '../components/ModeBadge.vue';
import ErrorMessage from '../components/ErrorMessage.vue';

const { connectionMode } = useBridge();
const { getInfo } = usePlugin(device);

const info = computed(() => getInfo.data.value as DeviceInfoResponse | null);
</script>

<template>
  <div>
    <h1>Device Plugin</h1>
    <ModeBadge :connectionMode="connectionMode" fallbackLabel="Fallback (Web)" />
    <div class="card">
      <h2>Device Information</h2>
      <button @click="getInfo.execute()">Get Device Info</button>
      <div v-if="info" class="result" style="margin-top: 1rem">
        <table class="info-table">
          <tbody>
            <tr v-for="[key, value] in Object.entries(info)" :key="key">
              <td>{{ key }}</td>
              <td>{{ String(value ?? 'N/A') }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <ErrorMessage :error="getInfo.error.value" />
  </div>
</template>

// examples/react/src/pages/DevicePage.tsx
import { usePlugin, useBridge } from '../bridge';
import { device } from '@example/plugins';
import type { DeviceInfoResponse } from '@example/plugins';
import ModeBadge from '../components/ModeBadge';
import ActionError from '../components/ActionError';

function DevicePage() {
  const { connectionMode } = useBridge();
  const { getInfo } = usePlugin(device);

  const handleGetInfo = () => getInfo.execute();

  const info = getInfo.data ? (getInfo.data as DeviceInfoResponse) : null;

  return (
    <div>
      <h1>Device Plugin</h1>
      <ModeBadge connectionMode={connectionMode} fallbackLabel="Web" />

      <div className="card">
        <h2>Device Information</h2>
        <button onClick={handleGetInfo}>Get Device Info</button>

        {info && (
          <div className="result" style={{ marginTop: '1rem' }}>
            <table className="info-table">
              <tbody>
                {Object.entries(info).map(([key, value]) => (
                  <tr key={key}>
                    <td>{key}</td>
                    <td>{String(value ?? 'N/A')}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      <ActionError error={getInfo.error} />
    </div>
  );
}

export default DevicePage;
