// examples/vue/src/pages/PhonePage.vue
<script setup lang="ts">
import { ref } from 'vue';
import { usePlugin, useBridge } from '../bridge';
import { phone } from '@example/plugins';
import ModeBadge from '../components/ModeBadge.vue';
import ErrorMessage from '../components/ErrorMessage.vue';

const { connectionMode } = useBridge();
const { call } = usePlugin(phone);
const number = ref('');

const handleDigit = (digit: string) => { number.value += digit; };
const handleDelete = () => { number.value = number.value.slice(0, -1); };

const digits = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '*', '0', '#'];
</script>

<template>
  <div>
    <h1>Phone</h1>
    <ModeBadge :connectionMode="connectionMode" />
    <div class="card">
      <input
        type="tel"
        v-model="number"
        placeholder="Phone number"
        class="input-tel"
      />
      <div class="dial-grid">
        <button
          v-for="digit in digits"
          :key="digit"
          class="button button-secondary dial-button"
          @click="handleDigit(digit)"
        >
          {{ digit }}
        </button>
      </div>
      <div class="button-group">
        <button class="button button-call" @click="call.execute({ number: number })" :disabled="!number">
          Call
        </button>
        <button class="button button-secondary" @click="handleDelete" :disabled="!number">
          Delete
        </button>
      </div>
    </div>
    <div v-if="call.data.value" class="result success">Dialing {{ number }}...</div>
    <ErrorMessage :error="call.error.value" />
  </div>
</template>

// examples/react/src/pages/PhonePage.tsx
import { useState } from 'react';
import { usePlugin, useBridge } from '../bridge';
import { phone } from '@example/plugins';
import ModeBadge from '../components/ModeBadge';
import ActionError from '../components/ActionError';

function PhonePage() {
  const { connectionMode } = useBridge();
  const { call } = usePlugin(phone);
  const [number, setNumber] = useState('');

  const handleCall = () => call.execute({ number });

  const handleDigit = (digit: string) => {
    setNumber((prev) => prev + digit);
  };

  const handleDelete = () => {
    setNumber((prev) => prev.slice(0, -1));
  };

  return (
    <div>
      <h1>Phone</h1>
      <ModeBadge connectionMode={connectionMode} />

      <div className="card">
        <input
          type="tel"
          value={number}
          onChange={(e) => setNumber(e.target.value)}
          placeholder="Phone number"
          className="dial-input"
        />

        <div className="dial-grid">
          {['1', '2', '3', '4', '5', '6', '7', '8', '9', '*', '0', '#'].map((digit) => (
            <button
              key={digit}
              className="button button-secondary"
              onClick={() => handleDigit(digit)}
            >
              {digit}
            </button>
          ))}
        </div>

        <div className="button-group">
          <button className="button button-call" onClick={handleCall} disabled={!number}>
            Call
          </button>
          <button className="button button-secondary" onClick={handleDelete} disabled={!number}>
            Delete
          </button>
        </div>
      </div>

      {call.data && <div className="result success">Dialing {number}...</div>}
      <ActionError error={call.error} />
    </div>
  );
}

export default PhonePage;
